// Creates the missing Supabase Auth identities for the 5 staging fixture
// users seeded by seed-tenant-fixtures.ts. Those User rows were created
// directly in Postgres and have no matching auth.users row, so nobody can
// actually log in as them. Reuses each existing User.id as the Auth user id
// (supported via AdminUserAttributes.id) so no DB rows are created or
// rewritten here — this script only ever reads Users/TenantMemberships and
// writes to Supabase Auth.
//
// Temporary passwords are written to .env.staging-test-accounts.local
// (gitignored via the repo's blanket ".env*" pattern) and are never logged.
import "./env";
import { randomBytes } from "crypto";
import fs from "fs";
import path from "path";
import { createClient } from "@supabase/supabase-js";
import { db } from "./db";
import { WISDOMQUANT_TENANT_ID, DEMO_ACADEMY_TENANT_ID } from "./seed-tenant-fixtures";

const CREDENTIALS_PATH = path.resolve(__dirname, "../../.env.staging-test-accounts.local");

const TARGET_ACCOUNTS = [
  { key: "STAGING_WISDOMQUANT_ADMIN", role: "Admin", tenant: "WisdomQuant", email: "wisdomquant-fixture-admin@example.test" },
  { key: "STAGING_WISDOMQUANT_LEARNER", role: "Learner", tenant: "WisdomQuant", email: "wisdomquant-fixture-learner@example.test" },
  { key: "STAGING_DEMOACADEMY_ADMIN", role: "Admin", tenant: "Demo Academy", email: "demoacademy-admin@example.test" },
  { key: "STAGING_DEMOACADEMY_LEARNER", role: "Learner", tenant: "Demo Academy", email: "demoacademy-learner@example.test" },
  { key: "STAGING_CROSS_TENANT", role: "Shared (cross-tenant)", tenant: "WisdomQuant + Demo Academy", email: "cross-tenant-user@example.test" },
] as const;

function tenantLabel(tenantId: string): string {
  if (tenantId === WISDOMQUANT_TENANT_ID) return "WisdomQuant";
  if (tenantId === DEMO_ACADEMY_TENANT_ID) return "Demo Academy";
  return tenantId;
}

async function main() {
  const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { persistSession: false },
  });

  const credentialLines: string[] = [];
  const report: { role: string; tenant: string; email: string; status: string }[] = [];

  for (const target of TARGET_ACCOUNTS) {
    const user = await db.user.findUniqueOrThrow({
      where: { email: target.email },
      include: { tenantMemberships: { select: { tenantId: true, role: true } } },
    });

    const membershipSummary = user.tenantMemberships
      .map((m) => `${tenantLabel(m.tenantId)}:${m.role}`)
      .join(", ");
    console.log(`[staging] Found fixture user ${target.email} (id=${user.id}) — memberships: ${membershipSummary}`);

    const { data: existing } = await admin.auth.admin.getUserById(user.id);

    if (existing?.user) {
      console.log(`[staging] Auth identity already exists for ${target.email} (id=${user.id}) — leaving password untouched.`);
      report.push({ role: target.role, tenant: target.tenant, email: target.email, status: "already-existed" });
      continue;
    }

    const password = randomBytes(18).toString("base64url");
    const { data: created, error } = await admin.auth.admin.createUser({
      id: user.id,
      email: target.email,
      password,
      email_confirm: true,
    });

    if (error || !created.user) {
      throw new Error(`Failed to create Auth user for ${target.email}: ${error?.message ?? "unknown error"}`);
    }
    if (created.user.id !== user.id) {
      throw new Error(
        `Auth user id mismatch for ${target.email}: expected ${user.id}, got ${created.user.id}. ` +
          "Refusing to proceed with a mismatched account.",
      );
    }

    console.log(`[staging] Created Auth identity for ${target.email} (id=${user.id}).`);
    credentialLines.push(`${target.key}_EMAIL=${target.email}`);
    credentialLines.push(`${target.key}_PASSWORD=${password}`);
    report.push({ role: target.role, tenant: target.tenant, email: target.email, status: "created" });
  }

  if (credentialLines.length > 0) {
    const header =
      `# Staging-only Supabase Auth test account passwords (project ${process.env.NEXT_PUBLIC_SUPABASE_URL}).\n` +
      `# Generated by scripts/staging/create-staging-auth-users.ts — gitignored, never commit.\n`;
    fs.writeFileSync(CREDENTIALS_PATH, header + credentialLines.join("\n") + "\n", { encoding: "utf8" });
    console.log(`[staging] Wrote ${credentialLines.length / 2} new credential(s) to ${CREDENTIALS_PATH}`);
  } else {
    console.log("[staging] No new credentials to write — all target accounts already existed.");
  }

  console.log("\n=== Summary ===");
  for (const r of report) {
    console.log(`${r.status === "created" ? "CREATED" : "EXISTED"} — ${r.role} / ${r.tenant} / ${r.email}`);
  }

  await db.$disconnect();
}

main().catch(async (err) => {
  console.error(err);
  await db.$disconnect().catch(() => {});
  process.exit(1);
});
